language: minimal

env:
  global:
    - CONDA_PKGS_DIRS="${HOME}/.cache/conda/pkgs"

matrix:
  fast_finish: true

  include:
    - os: linux
      env: PYTHON_VERSION="3.6"
    - os: linux
      env: PYTHON_VERSION="3.7"
    - os: linux
      env: PYTHON_VERSION="3.8"
    - os: osx
      env: PYTHON_VERSION="3.6"
    - os: osx
      env: PYTHON_VERSION="3.7"
    - os: osx
      env: PYTHON_VERSION="3.8"

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh;
    else
        curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
    fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - source "${HOME}/miniconda/etc/profile.d/conda.sh"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - travis_retry conda update --quiet --yes conda
  # Useful for debugging any issues with conda
  - conda info --all

install:
  # create a conda environment
  - travis_retry conda create --quiet --yes --name pyschildci python=${PYTHON_VERSION} pip setuptools
  - travis_retry conda activate pyschildci
  - travis_retry conda install --quiet --yes --update-deps --name pyschildci
        coverage
        codecov
        flake8
        pytest>=3.3.0
        pytest-cov>=2.4.0
  # install a bunch of the larger/compiled runtime dependencies with conda
  - travis_retry conda install --quiet --yes --update-deps --name pyschildci
        astropy>=3.0.0
        healpy
        matplotlib>=3.0.0
        numpy>=1.16.0
        scipy>=1.2.0
  # install this version
  - python -m pip install --editable .

script:
  - python -m flake8 .
  - python -m pytest --verbose --cov --pyargs pyschild

after_success:
  - python -m coverage report
  - python -m codecov --flags $(uname) python${PYTHON_VERSION/./}

before_cache:
  - travis_retry conda clean --quiet --yes --all
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  pip: true
  directories:
    - ${HOME}/.cache/conda/pkgs
